### ISSUE TITLE
Lời mời tham gia

### ISSUE THREAD

**Issue by winstonleedev** [anhthang/awesome-made-by-vietnameses#1]
Chào bạn, mình thấy bạn có cùng ý tưởng với mình. 

Mình thấy để stars của project khá hay + có vài project mình chưa biết nên đã mạn phép đưa về [project của mình](https://github.com/thanhphu/awesome-vietnamese)

Bạn xem có thiếu gì thì PR giúp mình nhé, bạn cũng có thể sử dụng list của mình để cải tiến theo ý của bạn.

**Comment by anhthang** [comment]
@thanhphu chào bạn, không ngờ là cũng có người trùng ý tưởng 😆

Mình cũng có dự định làm thêm một file README tiếng Việt, nếu bạn có thể PR được thì tốt quá.

Mình cũng đã tham khảo thêm một vài dự án từ repo của bạn qua bên này ở commit mới nhất. Cảm ơn bạn nhé. Nếu tìm thêm được nhiều dự án mới, mình sẽ PR cho cả project của bạn nhé.
